package texmath

// symbols maps a backslash command name to its finished MathML atom. Greek
// letters and most named functions become identifiers (<mi>); relations,
// binary operators, arrows and big operators become operators (<mo>) so the
// MathML reader's operator dictionary gives them the right spacing and, for
// big operators in display style, limit placement.
//
// This is a curated proof-of-concept set covering common prose mathematics,
// not the full LaTeX symbol table. Unknown commands fall back to an upright
// identifier in parseMacro, so the map only needs the cases where the visual
// glyph differs from the command name.
var symbols = map[string]string{
	// Lowercase Greek.
	"alpha":      "<mi>α</mi>",
	"beta":       "<mi>β</mi>",
	"gamma":      "<mi>γ</mi>",
	"delta":      "<mi>δ</mi>",
	"epsilon":    "<mi>ϵ</mi>",
	"varepsilon": "<mi>ε</mi>",
	"zeta":       "<mi>ζ</mi>",
	"eta":        "<mi>η</mi>",
	"theta":      "<mi>θ</mi>",
	"vartheta":   "<mi>ϑ</mi>",
	"iota":       "<mi>ι</mi>",
	"kappa":      "<mi>κ</mi>",
	"lambda":     "<mi>λ</mi>",
	"mu":         "<mi>μ</mi>",
	"nu":         "<mi>ν</mi>",
	"xi":         "<mi>ξ</mi>",
	"pi":         "<mi>π</mi>",
	"varpi":      "<mi>ϖ</mi>",
	"rho":        "<mi>ρ</mi>",
	"varrho":     "<mi>ϱ</mi>",
	"sigma":      "<mi>σ</mi>",
	"varsigma":   "<mi>ς</mi>",
	"tau":        "<mi>τ</mi>",
	"upsilon":    "<mi>υ</mi>",
	"phi":        "<mi>ϕ</mi>",
	"varphi":     "<mi>φ</mi>",
	"chi":        "<mi>χ</mi>",
	"psi":        "<mi>ψ</mi>",
	"omega":      "<mi>ω</mi>",

	// Uppercase Greek (only the ones that differ from Latin letters).
	"Gamma":   "<mi>Γ</mi>",
	"Delta":   "<mi>Δ</mi>",
	"Theta":   "<mi>Θ</mi>",
	"Lambda":  "<mi>Λ</mi>",
	"Xi":      "<mi>Ξ</mi>",
	"Pi":      "<mi>Π</mi>",
	"Sigma":   "<mi>Σ</mi>",
	"Upsilon": "<mi>Υ</mi>",
	"Phi":     "<mi>Φ</mi>",
	"Psi":     "<mi>Ψ</mi>",
	"Omega":   "<mi>Ω</mi>",

	// Binary operators.
	"times":  "<mo>×</mo>",
	"cdot":   "<mo>⋅</mo>",
	"div":    "<mo>÷</mo>",
	"pm":     "<mo>±</mo>",
	"mp":     "<mo>∓</mo>",
	"ast":    "<mo>∗</mo>",
	"star":   "<mo>⋆</mo>",
	"circ":   "<mo>∘</mo>",
	"bullet": "<mo>∙</mo>",
	"oplus":  "<mo>⊕</mo>",
	"otimes": "<mo>⊗</mo>",
	"cup":    "<mo>∪</mo>",
	"cap":    "<mo>∩</mo>",
	"setminus": "<mo>∖</mo>",
	"wedge":  "<mo>∧</mo>",
	"vee":    "<mo>∨</mo>",

	// Relations.
	"leq":     "<mo>≤</mo>",
	"le":      "<mo>≤</mo>",
	"geq":     "<mo>≥</mo>",
	"ge":      "<mo>≥</mo>",
	"neq":     "<mo>≠</mo>",
	"ne":      "<mo>≠</mo>",
	"approx":  "<mo>≈</mo>",
	"equiv":   "<mo>≡</mo>",
	"sim":     "<mo>∼</mo>",
	"simeq":   "<mo>≃</mo>",
	"cong":    "<mo>≅</mo>",
	"propto":  "<mo>∝</mo>",
	"in":      "<mo>∈</mo>",
	"notin":   "<mo>∉</mo>",
	"ni":      "<mo>∋</mo>",
	"subset":  "<mo>⊂</mo>",
	"supset":  "<mo>⊃</mo>",
	"subseteq": "<mo>⊆</mo>",
	"supseteq": "<mo>⊇</mo>",
	"ll":      "<mo>≪</mo>",
	"gg":      "<mo>≫</mo>",

	// Arrows.
	"to":            "<mo>→</mo>",
	"rightarrow":    "<mo>→</mo>",
	"Rightarrow":    "<mo>⇒</mo>",
	"leftarrow":     "<mo>←</mo>",
	"Leftarrow":     "<mo>⇐</mo>",
	"leftrightarrow": "<mo>↔</mo>",
	"Leftrightarrow": "<mo>⇔</mo>",
	"mapsto":        "<mo>↦</mo>",

	// Big operators.
	"sum":    "<mo>∑</mo>",
	"prod":   "<mo>∏</mo>",
	"coprod": "<mo>∐</mo>",
	"int":    "<mo>∫</mo>",
	"oint":   "<mo>∮</mo>",
	"iint":   "<mo>∬</mo>",
	"bigcup": "<mo>⋃</mo>",
	"bigcap": "<mo>⋂</mo>",

	// Miscellaneous symbols.
	"infty":   "<mi>∞</mi>",
	"partial": "<mi>∂</mi>",
	"nabla":   "<mo>∇</mo>",
	"forall":  "<mo>∀</mo>",
	"exists":  "<mo>∃</mo>",
	"neg":     "<mo>¬</mo>",
	"emptyset": "<mi>∅</mi>",
	"angle":   "<mi>∠</mi>",
	"prime":   "<mo>′</mo>",
	"hbar":    "<mi>ℏ</mi>",
	"ell":     "<mi>ℓ</mi>",
	"Re":      "<mi>ℜ</mi>",
	"Im":      "<mi>ℑ</mi>",
	"aleph":   "<mi>ℵ</mi>",
	"dots":    "<mo>…</mo>",
	"ldots":   "<mo>…</mo>",
	"cdots":   "<mo>⋯</mo>",
	"vdots":   "<mo>⋮</mo>",
	"ddots":   "<mo>⋱</mo>",

	// Named operators (upright identifiers).
	"sin":    "<mi>sin</mi>",
	"cos":    "<mi>cos</mi>",
	"tan":    "<mi>tan</mi>",
	"cot":    "<mi>cot</mi>",
	"sec":    "<mi>sec</mi>",
	"csc":    "<mi>csc</mi>",
	"arcsin": "<mi>arcsin</mi>",
	"arccos": "<mi>arccos</mi>",
	"arctan": "<mi>arctan</mi>",
	"sinh":   "<mi>sinh</mi>",
	"cosh":   "<mi>cosh</mi>",
	"tanh":   "<mi>tanh</mi>",
	"log":    "<mi>log</mi>",
	"ln":     "<mi>ln</mi>",
	"lg":     "<mi>lg</mi>",
	"exp":    "<mi>exp</mi>",
	"lim":    "<mo>lim</mo>",
	"max":    "<mo>max</mo>",
	"min":    "<mo>min</mo>",
	"sup":    "<mo>sup</mo>",
	"inf":    "<mo>inf</mo>",
	"det":    "<mi>det</mi>",
	"gcd":    "<mi>gcd</mi>",
	"deg":    "<mi>deg</mi>",
	"dim":    "<mi>dim</mi>",
	"ker":    "<mi>ker</mi>",
	"mod":    "<mi>mod</mi>",
}
